
pthread_create: pthread_create.c
	gcc -o pthread_create pthread_create.c -lpthread

pthread_join: pthread_join.c
	gcc -o pthread_join pthread_join.c -lpthread

pthread_detach: pthread_detach.c
	gcc -o pthread_detach pthread_detach.c -lpthread

pthread_mutex: pthread_mutex.c
	gcc -o pthread_mutex pthread_mutex.c -lpthread

clean:
	rm -rf pthread_create pthread_join pthread_detach pthread_mutex
